services:
  user-server:
    image: ${DOCKERHUB_USERNAME}/user-server:latest
    env_file:
      - .env

  order-server:
    image: ${DOCKERHUB_USERNAME}/order-server:latest
    env_file:
      - .env

  hub-server:
    image: ${DOCKERHUB_USERNAME}/hub-server:latest
    env_file:
      - .env

  delivery-server:
    image: ${DOCKERHUB_USERNAME}/delivery-server:latest
    env_file:
      - .env

