services:
  eureka-server:
    image: ${DOCKERHUB_USERNAME}/eureka-server:latest
    env_file:
      - .env
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${EUREKA_PORT}/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  gateway-server:
    image: ${DOCKERHUB_USERNAME}/gateway-server:latest
    env_file:
      - .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${GATEWAY_PORT}/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  firm-server:
    image: ${DOCKERHUB_USERNAME}/firm-server:latest
    env_file:
      - .env
    ports:
      - "${FIRM_PORT}:${FIRM_PORT}"
    depends_on:
      gateway-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  product-server:
    image: ${DOCKERHUB_USERNAME}/product-server:latest
    env_file:
      - .env
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"
    depends_on:
      gateway-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
